# ─────────────────────────────────────────────────────────────────────────────
# IMPORTANT: Update baseURL to the primary custom domain so sitemap/canonicals are correct
baseURL       = "https://hunger-ring.com/"
title         = "Hunger Ring"
languageCode  = "en-us"
themesDir     = "../../themes"
# ─────────────────────────────────────────────────────────────────────────────

[module]
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "media"
    target = "assets/media"
  [[module.mounts]]
    source = "media"
    target = "static/media"

[outputs]
  home = ["HTML", "RSS", "JSON", "FORMS"]

[params]
  env                = "production"
  primaryColor       = "teal"
  lightBackground    = "gray-100"
  darkBackground     = "slate-900"
  cardBackground     = "gray-50"
  cardBackgroundDark = "slate-800"
  cardBorderLight    = "gray-200"
  cardBorderDark     = "gray-700"

  enableSearch       = true

  [[params.social]]
    name = "instagram"
    url  = "https://www.instagram.com/suggls"
    icon = "/media/instagram.png"
    alt  = "Instagram"

[params.socialDefaults]
  size = "w-7 h-7"
  gap  = "gap-3"


[params.forms]
  action         = "https://submit-form.com/fTauiGyR7"
  successMessage = "Thanks! We’ll notify you when Hunger Ring is available."
  errorMessage   = "Sorry, something went wrong. Please try again."

[params.header]
  stickyMobile      = true
  stickyDesktop     = true
  CTAText           = "Contact"
  CTAURL            = "/contact"
  showPhoneOnMobile = false
  rightMenu         = false

[params.turnstile]
  enable  = true
  sitekey = "0x4AAAAAAB8Xlhe4_-six2GL"

[menu]
  [[menu.main]]
    name   = "Home"
    url    = "/"
    weight = 10

  [[menu.main]]
    name   = "About"
    url    = "/about"
    weight = 20

  [[menu.main]]
    name   = "FAQs"
    url    = "/#faqs"
    weight = 25

  [[menu.main]]
    name   = "Contact"
    url    = "/contact"
    weight = 30
